### ISSUE TITLE
Warn of failure to validate license title-content match

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-doi#66]
Followup to #55 

The license validation function assumes the licenses match when it's unable to validate the text against the name.  Instead, it should add a warning to the admin notification that a manual check is needed.

https://github.com/G-Node/gin-doi/blob/ad4935d4e1c65b90991491712228a51b054a7cec/cmd/gindoid/validation.go#L94-L105

**Comment by achilleas-k** [comment]
The license validation only works one way: It uses the name of the license from the datacite.yml to retrieve the full text and compare against the LICENSE file in the repository.  If this fails (because the license name wasn't exactly formatted as expected), it could also work the other way around to help with the manual checks: Read the contents of the LICENSE file, infer the name, and add it to the admin notification for manual validation.

**Comment by mpsonntag** [comment]
License validation has been refactored via PR #89.
