### ISSUE TITLE
Add ORCID to metadata even when it's missing the prefix

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-doi#70]
In the datacite.yml, we expect the author ID to be in the form `type:id`, e.g., `ORCID:0000-0001-2345-6789`.  Sometimes a user will enter their ORCID but without the prefix.  We should allow this and assume it's an ORCID when the prefix is missing, since that's the most commonly used author ID type.  The service should warn us when this happens so we can manually verify the ID.

**Comment by mpsonntag** [comment]
Issue is handled via PR #90.
